---
- hosts: all
  become: yes 
  tasks:
    - name: DNF Update
    - dnf:
        name: "*"
        state: latest
    - name: Chromium
    - dnf: 
        name: chromium
        state: present
    - name: thunderbird

      
